export default [
    { variant: 'tall', name: 'duo' },
    { variant: 'medium', name: 'aimee' },
    { variant: 'small', name: 'barry' },
    { variant: 'small', name: 'trio' },
    { variant: 'medium', name: 'thomas' },
    { variant: 'small', name: 'gregor' },
    { variant: 'small', name: 'oli' },
    { variant: 'medium', name: 'mark' },
    { variant: 'medium', name: 'suzy' },
    { variant: 'small', name: 'duo' },
    { variant: 'small', name: 'jason' },
    { variant: 'small', name: 'ivy' },
    { variant: 'small', name: 'simon' },
    { variant: 'large', name: 'trio' },
];
